# This file is centrally managed as a template file in https://github.com/canonical/solutions-engineering-automation
# To update the file:
# - Edit it in the canonical/solutions-engineering-automation repository.
# - Open a PR with the changes.
# - When the PR merges, the soleng-terraform bot will open a PR to the target repositories with the changes.
name: Release to Edge (test)

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master, main]
    paths-ignore:
      - "**.md"
      - "**.rst"


jobs:

  release:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - [ubuntu-latest]  # github hosted runners are amd64
            # Ubuntu_ARM64_4C_16G_01 is the github-hosted arm64 runner we have access to.
            # We prefer the github runners because they are smaller machines and save resources.
            # If we have issues with it, we can switch to the larger and more numerous self-hosted options:
            # - runs-on: [self-hosted, jammy, ARM64]
          - [Ubuntu_ARM64_4C_16G_01]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # This should dropped once it's implemented on charming-actions itself. https://github.com/canonical/charming-actions/issues/140
      - name: Install and configure lxd
        run: |
          set -x

          # Sometimes runners can have lxd installed, usually the lts stable branch.
          # Ensure we're always on the latest/stable release here.
          if snap list lxd; then
            sudo snap refresh lxd --channel=latest/stable
          else
            sudo snap install lxd --channel=latest/stable
          fi

          # Change the lxd daemon group from `lxd` to `adm`.
          # Runner users are in the `adm` group, but not always the `lxd` group,
          # so this ensures that the user can use lxc without sudo.
          while [ -n "$(snap changes --abs-time lxd | awk '/^[0-9]+/ { if ($4 == "-") { print $4 } }')" ]; do
            echo "waiting for in-progress changes to lxd snap..."
            sleep 1
          done
          sudo snap set lxd daemon.group=adm

          sudo lxd waitready
          sudo lxd init --auto

          # if docker is installed, fix firewall for lxd
          if sudo iptables -L DOCKER-USER; then
  ￼         sudo iptables -I DOCKER-USER -i lxdbr0 -j ACCEPT
  ￼         sudo iptables -I DOCKER-USER -o lxdbr0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
  ￼       fi

      - name: Pack and upload to charmhub
        uses: canonical/charming-actions/upload-charm@2.6.2
        with:
          # ensure it does not cause an upload
          credentials: none
          github-token: notoken
          # Ensure the charm is built in an isolated environment and on the correct base in an lxd container.
          destructive-mode: false
