name: Release to Edge

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  check:
    uses: ./.github/workflows/check.yaml
    secrets: inherit

  release:
    needs: check
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - [ubuntu-latest]  # github hosted runners are amd64
            # Ubuntu_ARM64_4C_16G_01 is the github-hosted arm64 runner we have access to.
            # We prefer the github runners because they are smaller machines and save resources.
            # If we have issues with it, we can switch to the larger and more numerous self-hosted options:
            # - runs-on: [self-hosted, jammy, ARM64]
          - [Ubuntu_ARM64_4C_16G_01]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize lxd  # This should dropped once it's implemented on charming-actions itself. https://github.com/canonical/charming-actions/issues/140
        uses: canonical/setup-lxd@v0.1.1

        # NOTE: this action only supports a single charm file output https://github.com/canonical/charming-actions/blob/2.4.0/src/services/charmcraft/charmcraft.ts#L193-L194
        # This is fine right now because the charm only has a single build per architecture,
        # so only one will be built here.
      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@2.6.2
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          # Ensure the charm is built in an isolated environment and on the correct base in an lxd container.
          destructive-mode: false
